jobPortal/jobPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobPortal/website/urls.py
from django.urls import path
from . import views
from .views import profile, delete_job_post, verify_job_post, apply_job, dashboard_tracer, delete_tracer, SearchJobsView, recommend_jobs, send_message, inbox

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),

    path('profile/<int:user_id>/', views.profile, name="profile"),

    path('user-logout/', views.user_logout, name="user-logout"),
    path('company_profile/', views.company_profile, name="company_profile"),
    path('post_job/', views.post_job, name="post_job"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('dashboard_post/', views.dashboard_post, name="dashboard_post"),
    path('dashboard/users/', views.dashboard_users, name='dashboard_users'),
    path('dashboard/users/delete/<str:username>/', views.delete_user, name='delete_user'),

    path('delete_job_post/<int:job_post_id>/', delete_job_post, name='delete_job_post'),
    path('verify_job_post/<int:job_post_id>/', verify_job_post, name='verify_job_post'),
    path('job_find/', views.job_find, name="job_find"),
    path('job_info/<int:job_post_id>', views.job_info, name="job_info"),
    path('apply/<int:job_posting_id>/', apply_job, name='apply_job'),

    path('view_applications/<int:job_post_id>/', views.view_applications, name='view_applications'),

    path('graduate_tracer/', views.graduate_tracer, name="graduate_tracer"),

    path('dashboard_tracer/', dashboard_tracer, name='dashboard_tracer'),
    path('delete_tracer/<str:username>/', delete_tracer, name='delete_tracer'),

    path('search/', SearchJobsView.as_view(), name='search_jobs'),

    path('home/', recommend_jobs, name='home'),  # Adjust the URL pattern accordingly

    #Message
    path('send-message/<int:recipient_id>/', send_message, name='send_message'),
    path('inbox/<int:recipient_id>/', inbox, name='inbox'),

    #peeps
    path('people/', views.people, name="people"),


]

jobPortal/website/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    user_stat = models.CharField(max_length=50, null=True, blank=True)
    skill_description = models.TextField(null=True, blank=True)


    def __str__(self):
        return self.user.username

class Employer(models.Model):
    user_profile = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='employer')
    company_name = models.CharField(max_length=255)
    company_address = models.CharField(max_length=255)
    company_email = models.EmailField()
    contact_number = models.CharField(max_length=15)
    company_logo = models.ImageField(upload_to='company_logo/', null=True, blank=True)
    company_desc = models.CharField(max_length=655, null=True, blank=True)
    

    def __str__(self):
        return self.user_profile.user.username
    
class JobPosting(models.Model):
    JOB_TYPE_CHOICES = [
    ('full_time', 'Full Time'),
    ('freelancer', 'Freelancer'),
    ('part_time', 'Part Time'),
    ('intern', 'Intern'),
    ]
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE, related_name='job_postings')
    job_title = models.CharField(max_length=255)
    job_description = models.TextField()
    job_requirements = models.TextField()
    job_location = models.CharField(max_length=255)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    job_type = models.CharField(max_length=20, choices=JOB_TYPE_CHOICES, default='full_time')
    application_deadline = models.DateField(null=True, blank=True)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.job_title} at {self.employer.company_name}"
    
    @property
    def num_applicants(self):
        return UserCV.objects.filter(job_posting=self).count()

    
class UserCV(models.Model):
    resume = models.FileField(upload_to='user_cvs/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job_posting = models.ForeignKey(JobPosting, on_delete=models.CASCADE)
    company = models.CharField(max_length=255)

    def __str__(self):
        return f"CV for {self.user.username} - {self.job_posting.job_title} at {self.company}"
    
class GraduateTracer(models.Model):
    COLLEGE_DEPARTMENT_CHOICES = [
        ('', 'Choose'),
        ('College of Information and Communication Technology (CICT)', 'College of Information and Communication Technology (CICT)'),
        ('College of Business Administration (CBA)', 'College of Business Administration (CBA)'),
        ('College of Architecture and Fine Arts (CAFA)', 'College of Architecture and Fine Arts (CAFA)'),
        ('College of Arts and Letters (CAL)', 'College of Arts and Letters (CAL)'),
        ('College of Criminal Justice Education (CCJE)', 'College of Criminal Justice Education (CCJE)'),
        ('College of Social Science and Philosophy (CSSP)', 'College of Social Science and Philosophy (CSSP)'),
        ('College of Home Economics (CHE)', 'College of Home Economics (CHE)'),
        ('College of Industrial Technology (CIT)', 'College of Industrial Technology (CIT)'),
        ('College of Nursing (CON)', 'College of Nursing (CON)'),
        ('College of Engineering (COE)', 'College of Engineering (COE)'),
        ('College of Education (COED)', 'College of Education (COED)'),
        ('College of Sports, Exercise and Recreation', 'College of Sports, Exercise and Recreation'),
        ('College of Science (CS)', 'College of Science (CS)'),
    ]

    YEAR_CHOICES = [
        ('', 'Select Year'),
        ('2010', '2010'),
        ('2011', '2011'),
        ('2012', '2012'),
        ('2013', '2013'),
        ('2014', '2014'),
        ('2015', '2015'),
        ('2016', '2016'),
        ('2017', '2017'),
        ('2018', '2018'),
        ('2019', '2019'),
        ('2020', '2020'),
        ('2021', '2021'),
        ('2022', '2022'),
        ('2023', '2023'),
        ('2024', '2024'),
    ]

    CIVIL_STATUS_CHOICES = [
        ('Single', 'Single'),
        ('Married', 'Married'),
        ('Separated', 'Separated'),
        ('Widowed', 'Widowed'),
        ('Other', 'Other'),
    ]

    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    ]

    AGE_CHOICES = [
        ('', 'Select Age'),
        ('Below 20', 'Below 20'),
        ('20-25', '20-25'),
        ('26-30', '26-30'),
        ('31-35', '31-35'),
        ('36-40', '36-40'),
        ('Above 40', 'Above 40'),
        ('Other', 'Other'),
    ]

    EDUCATION_LEVEL_CHOICES = [
        ('', 'Select'),
        ('Certificate in Two Year Course', 'Certificate in Two Year Course'),
        ('College Graduate', 'College Graduate'),
        ('with Units in Masters Degree', 'with Units in Masters Degree'),
        ('Masters Degree Holder', 'Masters Degree Holder'),
        ('with Doctoral Degree', 'with Doctoral Degree'),
        ('Doctoral Degree Holder', 'Doctoral Degree Holder'),
    ]

    SCHOLARSHIP_CHOICES = [
        ('', 'Select'),
        ('Yes, I am a recipient of a GOVERTNMENT scholarship program', 'Yes, I am a recipient of a GOVERTNMENT scholarship program'),
        ('Yes, I am recipient of a PRIVATE scholarship program', 'Yes, I am recipient of a PRIVATE scholarship program'),
        ('No, I am not a recipient of ANY scholarship program', 'No, I am not a recipient of ANY scholarship program'),
    ]

    EMPLOYMENT_CHOICES = [
        ('', 'Select'),
        ('Yes', 'Yes'),
        ('No', 'No'),
        ('Never', 'Never'),
    ]

    EMPLOYMENT_STATUS_CHOICES = [
        ('', 'Select'),
        ('Regular/Permanent', 'Regular/Permanent'),
        ('Contractual', 'Contractual'),
        ('Temporary', 'Temporary'),
        ('Self-Employed', 'Self-Employed'),
    ]

    LINE_OF_BUSINESS_CHOICES = [
        ('', 'Select'),
        ('Agriculture', 'Agriculture'),
        ('Hunting and Forestry', 'Hunting and Forestry'),
        ('Fishing', 'Fishing'),
        ('Mining', 'Mining'),
        ('Construction', 'Construction'),
        ('Manufacturing', 'Manufacturing'),
        ('Transportation', 'Transportation'),
        ('Communication', 'Communication'),
        ('Finance', 'Finance'),
        ('Real Estate', 'Real Estate'),
        ('Education', 'Education'),
        ('Healthcare', 'Healthcare'),
        ('Technology', 'Technology'),
        ('Retail', 'Retail'),
        ('Hospitality', 'Hospitality'),
        ('Arts and Entertainment', 'Arts and Entertainment'),
        ('Other', 'Other'),
    ]

    WORK_PLACE_CHOICES = [
        ('', 'Select'),
        ('Local', 'Local'),
        ('Abroad', 'Abroad'),
    ]

    FIRST_JOB_CHOICES = [
        ('', 'Select'),
        ('Yes', 'Yes'),
        ('No', 'No'),
    ]

    FIRST_JOB_RELATED_CHOICES = [
        ('', 'Select'),
        ('Yes', 'Yes'),
        ('No', 'No'),
    ]

    FIRST_JOB_DURATION_CHOICES = [
        ('', 'Select'),
        ('less than a month', 'Less than a month'),
        ('1 to 6 months', '1 to 6 months'),
        ('7 to 11 months', '7 to 11 months'),
        ('1 year to less than 2 years', '1 year to less than 2 years'),
        ('2 years to less than 3 years', '2 years to less than 3 years'),
        ('3 years to less than 4 years', '3 years to less than 4 years'),
        ('Other', 'Other'),
    ]

    FIRST_JOB_LAND_DURATION_CHOICES = [
        ('', 'Select'),
        ('less than a month', 'Less than a month'),
        ('1 to 6 months', '1 to 6 months'),
        ('7 to 11 months', '7 to 11 months'),
        ('1 year to less than 2 years', '1 year to less than 2 years'),
        ('2 years to less than 3 years', '2 years to less than 3 years'),
        ('3 years to less than 4 years', '3 years to less than 4 years'),
        ('Other', 'Other'),
    ]

    MONTHLY_EARNING_CHOICES = [
        ('', 'Select'),
        ('Below ₱5,000,00', 'Below ₱5,000,00'),
        ('₱5,000,00 to less than ₱10,000,00', '₱5,000,00 to less than ₱10,000,00'),
        ('₱10,000,00 to ₱15,000,00', '₱10,000,00 to ₱15,000,00'),
        ('₱15,000,00 to ₱20,000,00', '₱15,000,00 to ₱20,000,00'),
        ('₱20,000,00 to ₱25,000,00', '₱20,000,00 to ₱25,000,00'),
        ('₱25,000,00 to ₱30,000,00', '₱25,000,00 to ₱30,000,00'),
        ('Other', 'Other'),
    ]

    CURRICULUM_RELEVANCE_CHOICES = [
        ('', 'Select'),
        ('Yes', 'Yes'),
        ('No', 'No'),
    ]

    # Reference the Signup model using a ForeignKey
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    college_department = models.CharField(max_length=255, choices=COLLEGE_DEPARTMENT_CHOICES, default='',)
    course = models.CharField(max_length=255, blank=True, null=True)
    year_graduated = models.CharField(max_length=4, choices=YEAR_CHOICES, default='',)
    fullname = models.CharField(max_length=255, blank=True, null=True)
    civil_status = models.CharField(max_length=10, choices=CIVIL_STATUS_CHOICES, default='Other')
    age = models.CharField( max_length=10, choices=AGE_CHOICES, default='')
    address = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='Other')
    email = models.EmailField(blank=True, null=True)
    contact = models.CharField(max_length=20, blank=True, null=True)
    education_level = models.CharField(max_length=50, choices=EDUCATION_LEVEL_CHOICES, default='')

jobPortal/website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import UserProfile, Employer, JobPosting, UserCV, GraduateTracer


class CreateUserForm(UserCreationForm):

    email = forms.EmailField(required=True, error_messages={'required': 'email required.'})
    first_name = forms.CharField(max_length=30, error_messages={'required': 'first name required.'})
    last_name = forms.CharField(max_length=30, error_messages={'required': 'last name required.'})
    user_stat = forms.ChoiceField(choices=[('jobSeeker', 'Job Seeker'), ('employer', 'Employer')])
    password1 = forms.CharField(widget=forms.PasswordInput, required=True, error_messages={'required': 'Please enter a password.'})
    password2 = forms.CharField(widget=forms.PasswordInput, required=True, error_messages={'required': 'Please re-enter your password.'})

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1', 'password2', 'user_stat']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email address is already in use. Please use a different email.')
        return email
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('The passwords do not match. Please enter the same password in both fields.')
        return password2

class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic','phone_number', 'address', 'gender', 'skill_description']
        # Add other fields as needed

class EmployerEditForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = ['company_name','company_address', 'company_email', 'contact_number', 'company_logo', 'company_desc']
        # Add other fields as needed

class JobPostingForm(forms.ModelForm):
    class Meta:
        model = JobPosting
        fields = ['job_title','job_description', 'job_requirements', 'job_location', 'salary', 'application_deadline', 'job_type']
        # Add other fields as needed

class UserCVForm(forms.ModelForm):
    class Meta:
        model = UserCV
        fields = ['resume']

class GraduateTracerForm(forms.ModelForm):
    class Meta:
        model = GraduateTracer
        exclude = ['user']  # Exclude the 'user' field from the form, as it will be set in the view

jobPortal/website/templates/post_job.html
{% extends "base/base.html" %}
{% load static %}

{% block template %}
    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    
    {% include "base/navbar.html" %}

    <!-- HOME -->
    <section class="section-hero overlay inner-page bg-image" style="background-image: url('{% static 'website/images/hero_1.jpg' %}');" id="home-section">
        <div class="container">
            <div class="row">
              <div class="col-md-7">
                <h1 class="text-white font-weight-bold">Post a Job</h1>
                <div class="custom-breadcrumbs">
                  <a href="{% url 'home' %}">Home</a> <span class="mx-2 slash">/</span>
                  <span class="text-white"><strong>Post Job</strong></span>
                </div>
              </div>
            </div>
          </div>
    </section>

    <!-- JOB POST FORM -->
    <section class="site-section" id="post-job-section">
        <div class="container">
            <div class="row justify-content-center mb-5">
                <div class="col-md-7 text-center">
                    <h2 class="section-title mb-2">Post a Job</h2>
                </div>
            </div>

            <div class="row justify-content-center">
                <div class="col-md-7">
                    <form method="post" action="{% url 'post_job' %}">
                        {% csrf_token %}
                        
                        <!-- Employer (Hidden Input Field) -->
                        <input type="hidden" name="employer" value="{{ user.userprofile.employer.id }}">

                        <!-- Job Title -->
                        <div class="form-group">
                            <label for="id_job_title">Job Title</label>
                            <input type="text" name="job_title" class="form-control" id="id_job_title" required autocomplete="off">
                        </div>

                        <!-- Job Description -->
                        <div class="form-group">
                            <label for="id_job_description">Job Description</label>
                            <textarea name="job_description" class="form-control" id="id_job_description" rows="5" required></textarea>
                        </div>

                        <!-- Job Requirements -->
                        <div class="form-group">
                            <label for="id_job_requirements">Job Requirements</label>
                            <textarea name="job_requirements" class="form-control" id="id_job_requirements" rows="5" required></textarea>
                        </div>

                        <!-- Job Type -->
                        <div class="form-group">
                            <label for="id_job_type">Job Type</label>
                            <select name="job_type" class="form-control" id="id_job_type" required>
                                <option value="full_time">Full Time</option>
                                <option value="freelancer">Freelancer</option>
                                <option value="part_time">Part Time</option>
                                <option value="intern">Intern</option>
                            </select>
                        </div>

                        <!-- Job Location -->
                        <div class="form-group">
                            <label for="id_job_location">Job Location</label>
                            <input type="text" name="job_location" class="form-control" id="id_job_location" required>
                        </div>

                        <!-- Salary -->
                        <div class="form-group">
                            <label for="id_salary">Salary</label>
                            <input type="number" name="salary" class="form-control" id="id_salary" required>
                        </div>

                        <!-- Application Deadline -->
                        <div class="form-group">
                            <label for="id_application_deadline">Application Deadline (Optional)</label>
                            <input type="date" name="application_deadline" class="form-control" id="id_application_deadline">
                        </div>

                        <!-- Submit Button -->
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Post Job</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    {% include "base/footer.html" %}
{% endblock %}

jobPortal/website/templates/profile.html
{% extends "base/base.html" %}
{% load static %}

{% block template %}

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    

    <!-- NAVBAR -->
    {% include "base/navbar.html" %}

    <!-- HOME -->
    <section class="section-hero overlay inner-page bg-image" style="background-image: url('{%static 'website/images/hero_1.jpg'%}');" id="home-section">
    </section>

    <!-- PROFILE -->
    <section class="site-section" id="profile-section">
      <div class="container">
        <div class="main-body">
          <div class="row">
            <div class="col-lg-4">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if user.userprofile and user.userprofile.profile_pic %}
                      <img src="{{ user.userprofile.profile_pic.url }}" alt="{{ user.get_full_name }}" class="rounded-circle p-1 bg-primary" width="110">
                    {% else %}
                      <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="{{ user.get_full_name }}" class="rounded-circle p-1 bg-primary" width="110">
                    {% endif %}
                    <div class="mt-3">
                          <h4>{{ user.get_full_name }}</h4>
                          <p class="text-secondary mb-1">{{ user.email }}</p>
                          {% if user != request.user %}
                              <a href="{% url 'send_message' recipient_id=user.id %}" class="btn btn-primary">Message</a>
                          {% endif %}

                          {% if user == request.user %}
                              <!-- Show the edit icon only for the owner of the profile -->
                              <a href="#" data-toggle="modal" data-target="#editProfileModal">
                                <i class="mr-2 icon-pencil"></i> Edit
                              </a>
                          {% endif %}
                  </div>
                  </div>
                  <hr class="my-4">
                  <ul class="list-group list-group-flush">
                    <div class="mt-3 align-items-center text-center">
                      {% if user.userprofile.user_stat == 'employer' and user == request.user %}
                          <a href="{% url 'company_profile' %}" class="btn btn-primary text-center">Company Profile</a>
                      {% endif %}
                    </div>
                    {% if user == request.user %}
                      <div class="mt-3 align-items-center text-center">
                        <a href="{% url 'user-logout' %}" class="btn btn-danger text-center">Logout</a>
                      </div>
                      <div class="mt-3 align-items-center text-center">
                        <a href="{% url 'graduate_tracer' %}" class="btn btn-secondary text-center">Graduate Tracer</a>
                      </div>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-lg-8">
              <div class="card">
                <div class="card-body">
                  <div class="row mb-3">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <input type="text" class="form-control" value="{{ user.get_full_name  }}" disabled>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <input type="text" class="form-control" value="{{ user.email  }}" disabled>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {% if user.userprofile %}
                            <input type="text" class="form-control" value="{{ user.userprofile.phone_number }}" disabled>
                        {% else %}
                            <input type="text" class="form-control" value="N/A" disabled>
                        {% endif %}
                    </div>
                </div>
                  <div class="row mb-3">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {% if user.userprofile %}
                      <input type="text" class="form-control" value="{{ user.userprofile.address }}" disabled>
                      {% else %}
                         <input type="text" class="form-control" value="N/A" disabled>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
              <div class="row mt-2">
                <div class="col-sm-12">
                  <div class="card">
                    <div class="card-body">
                      <h5 class="d-flex align-items-center mb-3">Skill Descriptions</h5>
                      <p>{{ user.userprofile.skill_description }}</p>
                    </div>
                    <div class="mt-3 align-items-center text-center">
                  </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>



<!-- Fixed message icon in the bottom right corner -->
<div class="position-fixed" style="bottom: 40px; right: 40px;"> <!-- Adjust the bottom and right margins as needed -->
  <a href="{% url 'inbox' request.user.id %}" class="btn btn-primary text-center fixed-message-icon">
      <i class="icon-mail_outline" style="font-size: 40px;"></i> <!-- Adjust the font size as needed -->
  </a>
</div>


    </section>


   <!-- Bootstrap Modal for Edit Profile -->
<div class="modal fade" id="editProfileModal" tabindex="-1" role="dialog" aria-labelledby="editProfileModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editProfileModalLabel">Edit Profile</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <!-- Add your form fields for editing profile details here -->
        <form method="post" action="{% url 'profile' user.id %}" enctype="multipart/form-data">
          {% csrf_token %}

          <!-- Profile Picture -->
          <div class="form-group">
            <label for="id_profile_pic">Profile Picture</label>
            {% if user.userprofile and user.userprofile.profile_pic %}
                <img src="{{ user.userprofile.profile_pic.url }}" alt="{{ user.get_full_name }}" class="img-thumbnail" style="max-width: 150px; max-height: 150px;">
            {% else %}
                <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="{{ user.get_full_name }}" class="img-thumbnail" style="max-width: 150px; max-height: 150px;">
            {% endif %}
            <input type="file" name="profile_pic" accept="image/*" class="form-control" id="id_profile_pic">
            <small class="form-text text-muted">Choose a new profile picture or leave it empty to keep the current one.</small>
          </div>

          <!-- Gender -->
          <div class="form-group">
            <label for="id_gender">Gender</label>
            <select name="gender" class="form-control" id="id_gender">
              <option value="male" {% if user.userprofile.gender == 'male' %}selected{% endif %}>Male</option>
              <option value="female" {% if user.userprofile.gender == 'female' %}selected{% endif %}>Female</option>
              <option value="other" {% if user.userprofile.gender == 'other' %}selected{% endif %}>Other</option>
            </select>
          </div>
        
          <!-- Phone Number -->
          <div class="form-group">
            <label for="id_phone_number">Phone Number</label>
            <input type="tel" name="phone_number" class="form-control" id="id_phone_number" value="{{ user.userprofile.phone_number }}">
          </div>
        
          <!-- Address -->
          <div class="form-group">
            <label for="id_address">Address</label>
            <input type="text" name="address" class="form-control" id="id_address" value="{{ user.userprofile.address }}">
          </div>

          <!-- skill description -->
          <div class="form-group">
            <label for="skill_description">skill Description</label>
            <textarea name="skill_description" class="form-control" id="skill_description" value="{{ user.userprofile.skill_description }}">{{ user.userprofile.skill_description }}</textarea>
          </div>
        
          <!-- Add more form fields as needed -->
        
          <!-- Submit Button -->
          <div class="row form-group">
            <div class="col-md-12 text-center">
              <input type="submit" value="Save Changes" class="btn px-4 btn-primary text-white">
            </div>
          </div>

        </form>
      </div>
    </div>
  </div>
</div>


{% include "base/footer.html" %}
{% endblock %}